/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AcceptBtn: typeof import('./src/components/ui/main/actions/AcceptBtn.vue')['default']
    AppHeader: typeof import('./src/components/ui/header/AppHeader.vue')['default']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    CloseBtn: typeof import('./src/components/ui/main/actions/CloseBtn.vue')['default']
    CreateBtn: typeof import('./src/components/ui/main/actions/CreateBtn.vue')['default']
    ICarbonChevronRight: typeof import('~icons/carbon/chevron-right')['default']
    IClarityCloseLine: typeof import('~icons/clarity/close-line')['default']
    IClarityFileLine: typeof import('~icons/clarity/file-line')['default']
    IClarityLoginLine: typeof import('~icons/clarity/login-line')['default']
    IClarityMenuLine: typeof import('~icons/clarity/menu-line')['default']
    IClarityMoonLine: typeof import('~icons/clarity/moon-line')['default']
    IClarityNoteLine: typeof import('~icons/clarity/note-line')['default']
    IClaritySearchLine: typeof import('~icons/clarity/search-line')['default']
    IClaritySettingsLine: typeof import('~icons/clarity/settings-line')['default']
    IClaritySunLine: typeof import('~icons/clarity/sun-line')['default']
    IClarityUserLine: typeof import('~icons/clarity/user-line')['default']
    IconBtn: typeof import('./src/components/ui/header/actions/IconBtn.vue')['default']
    IMdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    IMdiLightEye: typeof import('~icons/mdi-light/eye')['default']
    IMdiLightEyeOff: typeof import('~icons/mdi-light/eye-off')['default']
    IMdiLightLabel: typeof import('~icons/mdi-light/label')['default']
    MenuIcon: typeof import('./src/components/icons/MenuIcon.vue')['default']
    MoonIcon: typeof import('./src/components/icons/MoonIcon.vue')['default']
    NoteBackBtn: typeof import('./src/components/ui/header/actions/NoteBackBtn.vue')['default']
    NoteList: typeof import('./src/components/ui/main/NoteList.vue')['default']
    NotificationIcon: typeof import('./src/components/icons/NotificationIcon.vue')['default']
    PasswordInput: typeof import('./src/components/forms/custom/PasswordInput.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/ui/header/SearchBar.vue')['default']
    SearchIcon: typeof import('./src/components/icons/SearchIcon.vue')['default']
    SideBar: typeof import('./src/components/ui/header/SideBar.vue')['default']
    SunIcon: typeof import('./src/components/icons/SunIcon.vue')['default']
    TextareaInput: typeof import('./src/components/forms/custom/TextareaInput.vue')['default']
    TextInput: typeof import('./src/components/forms/custom/TextInput.vue')['default']
    UserMenu: typeof import('./src/components/ui/header/UserMenu.vue')['default']
  }
}
