/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AcceptBtn: typeof import('./src/components/ui/main/actions/AcceptBtn.vue')['default']
    AppHeader: typeof import('./src/components/ui/header/AppHeader.vue')['default']
    AppLogo: typeof import('./src/components/AppLogo.vue')['default']
    CloseBtn: typeof import('./src/components/ui/main/actions/CloseBtn.vue')['default']
    CreateBtn: typeof import('./src/components/ui/main/actions/CreateBtn.vue')['default']
    IBiArrowLeft: typeof import('~icons/bi/arrow-left')['default']
    ICarbonArrowLeft: typeof import('~icons/carbon/arrow-left')['default']
    ICarbonNewTab: typeof import('~icons/carbon/new-tab')['default']
    ICircumCirclePlus: typeof import('~icons/circum/circle-plus')['default']
    ICircumClarityPlus: typeof import('~icons/circum/clarity-plus')['default']
    'ICircumClarityPlus=line': typeof import('~icons/circum/clarity-plus=line')['default']
    ICircumClarityPlusLine: typeof import('~icons/circum/clarity-plus-line')['default']
    ICircumSearch: typeof import('~icons/circum/search')['default']
    ICircumSquarePlus: typeof import('~icons/circum/square-plus')['default']
    ICircumUser: typeof import('~icons/circum/user')['default']
    IClarityCloseLine: typeof import('~icons/clarity/close-line')['default']
    IClarityCrossLine: typeof import('~icons/clarity/cross-line')['default']
    IClarityFileLine: typeof import('~icons/clarity/file-line')['default']
    IClarityMenuLine: typeof import('~icons/clarity/menu-line')['default']
    'IClarityNote-': typeof import('~icons/clarity/note-')['default']
    IClarityNoteLine: typeof import('~icons/clarity/note-line')['default']
    IClarityPlusLine: typeof import('~icons/clarity/plus-line')['default']
    IClaritySearchLine: typeof import('~icons/clarity/search-line')['default']
    IClaritySortByLine: typeof import('~icons/clarity/sort-by-line')['default']
    IClarityUserLine: typeof import('~icons/clarity/user-line')['default']
    IconBtn: typeof import('./src/components/ui/header/actions/IconBtn.vue')['default']
    ILaArrowLeft: typeof import('~icons/la/arrow-left')['default']
    IMdiArrowLeft: typeof import('~icons/mdi/arrow-left')['default']
    IMdiLightHome: typeof import('~icons/mdi-light/home')['default']
    IMdiLightLabel: typeof import('~icons/mdi-light/label')['default']
    IMdiLightLogin: typeof import('~icons/mdi-light/login')['default']
    IMdiLLogin: typeof import('~icons/mdi/l-login')['default']
    IMdiYoutube: typeof import('~icons/mdi/youtube')['default']
    INimbusArrowLeft: typeof import('~icons/nimbus/arrow-left')['default']
    MenuIcon: typeof import('./src/components/icons/MenuIcon.vue')['default']
    NoteBackBtn: typeof import('./src/components/ui/header/actions/NoteBackBtn.vue')['default']
    NoteList: typeof import('./src/components/ui/main/NoteList.vue')['default']
    NotificationIcon: typeof import('./src/components/icons/NotificationIcon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchIcon: typeof import('./src/components/icons/SearchIcon.vue')['default']
    SideBar: typeof import('./src/components/ui/header/SideBar.vue')['default']
    TextareaInput: typeof import('./src/components/forms/TextareaInput.vue')['default']
    TextInput: typeof import('./src/components/forms/TextInput.vue')['default']
  }
}
