<template>
  <Transition name="search-bar">
    <div
      v-show="action.searchBar"
      class="flex rounded-full bg-slate-300 px-3 items-center w-36 sm:w-3/4 h-7">
      <i-clarity-search-line
        class="text-slate-500 text-base"></i-clarity-search-line>
      <input
        ref="search"
        aria-label="search"
        class="bg-transparent focus:outline-none w-full pl-5"
        placeholder="Search...."
        type="search" />
    </div>
  </Transition>
</template>

<script setup lang="ts">
  import { ref } from "vue";
  import { useActionStore } from "../../../stores/useActionStore";
  const action = useActionStore();
  const search = ref();

  if (action.searchBar) {
    search.value.focus();
  }
</script>

<style scoped>
  .search-bar-leave-active {
    -webkit-animation: scale-out-hor-right 250ms
      cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
    animation: scale-out-hor-right 250ms cubic-bezier(0.55, 0.085, 0.68, 0.53)
      both;
  }
  @-webkit-keyframes scale-out-hor-right {
    0% {
      -webkit-transform: scaleX(1);
      transform: scaleX(1);
      -webkit-transform-origin: 100% 100%;
      transform-origin: 100% 100%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scaleX(0);
      transform: scaleX(0);
      -webkit-transform-origin: 100% 100%;
      transform-origin: 100% 100%;
      opacity: 1;
    }
  }
  @keyframes scale-out-hor-right {
    0% {
      -webkit-transform: scaleX(1);
      transform: scaleX(1);
      -webkit-transform-origin: 100% 100%;
      transform-origin: 100% 100%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scaleX(0);
      transform: scaleX(0);
      -webkit-transform-origin: 100% 100%;
      transform-origin: 100% 100%;
      opacity: 1;
    }
  }

  .search-bar-enter-active {
    -webkit-animation: scale-in-hor-right 250ms
      cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    animation: scale-in-hor-right 250ms cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  }

  /* ----------------------------------------------
 * Generated by Animista on 2023-4-4 14:47:18
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation scale-in-hor-right
 * ----------------------------------------
 */
  @-webkit-keyframes scale-in-hor-right {
    0% {
      -webkit-transform: scaleX(0);
      transform: scaleX(0);
      -webkit-transform-origin: 100% 100%;
      transform-origin: 100% 100%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scaleX(1);
      transform: scaleX(1);
      -webkit-transform-origin: 100% 100%;
      transform-origin: 100% 100%;
      opacity: 1;
    }
  }
  @keyframes scale-in-hor-right {
    0% {
      -webkit-transform: scaleX(0);
      transform: scaleX(0);
      -webkit-transform-origin: 100% 100%;
      transform-origin: 100% 100%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scaleX(1);
      transform: scaleX(1);
      -webkit-transform-origin: 100% 100%;
      transform-origin: 100% 100%;
      opacity: 1;
    }
  }
</style>
