<template>
  <Transition name="user-menu">
    <div
      v-show="action.userMenu"
      class="absolute -top-4 right-0 z-10 bg-base-100 p-5 shadow rounded-b-md">
      <nav>
        <ul class="flex flex-col justify-center gap-2">
          <li>
            <router-link to="/">
              <button
                class="btn btn-sm btn-ghost flex gap-2 items-center rounded-sm">
                <i-clarity-user-line></i-clarity-user-line>
                <span class="text-sm font-normal capitalize">Profile</span>
              </button>
            </router-link>
          </li>
          <li>
            <button
              class="btn btn-sm btn-ghost flex gap-2 items-center rounded-sm">
              <i-clarity-moon-line></i-clarity-moon-line>
              <span class="text-sm font-normal capitalize">Dark Mode</span>
            </button>
          </li>
          <li>
            <router-link to="/">
              <button
                class="btn btn-sm btn-ghost flex gap-2 items-center rounded-sm">
                <i-clarity-settings-line></i-clarity-settings-line>
                <span class="text-sm font-normal capitalize">Settings</span>
              </button>
            </router-link>
          </li>
          <li>
            <router-link to="/login">
              <button
                class="btn btn-sm btn-ghost flex gap-2 items-center rounded-sm">
                <i-clarity-login-line></i-clarity-login-line>
                <span class="text-sm font-normal capitalize">Login</span>
              </button>
            </router-link>
          </li>
        </ul>
      </nav>
    </div>
  </Transition>
</template>

<script setup lang="ts">
  import { useActionStore } from "../../../stores/useActionStore";

  const action = useActionStore();
</script>

<style scoped>
  .user-menu-enter-active {
    -webkit-animation: scale-in-ver-top 0.5s
      cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
    animation: scale-in-ver-top 0.5s cubic-bezier(0.25, 0.46, 0.45, 0.94) both;
  }
  /* ----------------------------------------------
 * Generated by Animista on 2023-4-4 14:0:17
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation scale-in-ver-top
 * ----------------------------------------
 */
  @-webkit-keyframes scale-in-ver-top {
    0% {
      -webkit-transform: scaleY(0);
      transform: scaleY(0);
      -webkit-transform-origin: 100% 0%;
      transform-origin: 100% 0%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scaleY(1);
      transform: scaleY(1);
      -webkit-transform-origin: 100% 0%;
      transform-origin: 100% 0%;
      opacity: 1;
    }
  }
  @keyframes scale-in-ver-top {
    0% {
      -webkit-transform: scaleY(0);
      transform: scaleY(0);
      -webkit-transform-origin: 100% 0%;
      transform-origin: 100% 0%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scaleY(1);
      transform: scaleY(1);
      -webkit-transform-origin: 100% 0%;
      transform-origin: 100% 0%;
      opacity: 1;
    }
  }

  .user-menu-leave-active {
    -webkit-animation: scale-out-ver-top 0.5s
      cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
    animation: scale-out-ver-top 0.5s cubic-bezier(0.55, 0.085, 0.68, 0.53) both;
  }

  /* ----------------------------------------------
 * Generated by Animista on 2023-4-4 14:2:5
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info. 
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

  /**
 * ----------------------------------------
 * animation scale-out-ver-top
 * ----------------------------------------
 */
  @-webkit-keyframes scale-out-ver-top {
    0% {
      -webkit-transform: scaleY(1);
      transform: scaleY(1);
      -webkit-transform-origin: 100% 0%;
      transform-origin: 100% 0%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scaleY(0);
      transform: scaleY(0);
      -webkit-transform-origin: 100% 0%;
      transform-origin: 100% 0%;
      opacity: 1;
    }
  }
  @keyframes scale-out-ver-top {
    0% {
      -webkit-transform: scaleY(1);
      transform: scaleY(1);
      -webkit-transform-origin: 100% 0%;
      transform-origin: 100% 0%;
      opacity: 1;
    }
    100% {
      -webkit-transform: scaleY(0);
      transform: scaleY(0);
      -webkit-transform-origin: 100% 0%;
      transform-origin: 100% 0%;
      opacity: 1;
    }
  }
</style>
